version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: apigateway-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb-data:
    name: apigateway-mongodb-data

