spring:
  application:
    name: apigateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-query-service
              uri: http://localhost:8081
              predicates:
                - Path=/products/query/**
                - Method=GET
              filters:
                - RewritePath=/products/query(?<segment>.*), /products$\{segment}
            - id: product-service
              uri: http://localhost:8081
              predicates:
                - Path=/products/**
                - Method=POST
              filters:
                - TokenParsingFilter
            - id: auth-service
              uri: http://localhost:8082
              predicates:
                - Path=/auth/**